### ISSUE TITLE
Create biotope flavor

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE-flavors#25]
Create a new biotope flavor with:

- Conda environment:

```yaml
name: biotope
channels:
  - conda-forge
dependencies:
  - r-irkernel
  - r-jsonlite
  - r-optparse
  - r=4.1.0
  - python=3.10
  - ipykernel
  - pip
  - openssl
  - curl
  - wget
  - cmake
  - r-shiny
  - r-knitr
  - r-devtools
  - r-optparse
  - r-tidyverse
  - r-here
  - r-rgbif=3.6.0
  - r-lubridate  
  - r-base
  - r-glue
  - r-RSQLite
  - r-sp
  - r-data.table
  - zip
  - unzip
  - pandas
  - gdal
  - pyproj
  - shapely
```

- Manual installations in Docker file

```Dockerfile
RUN R -e devtools::install_github('trias-project/trias@5d0f27f76567c0d11021a3055c32ec521622ca36')
```

- OTB as installed in: https://github.com/Ckkk112138/biotope/blob/main/ZonalFilter/Dockerfile
