### ISSUE TITLE
Add `git` to all flavors

### ISSUE THREAD

**Issue by gpelouze** [QCDIS/NaaVRE-flavors#33]
If a cell contains

```yaml
name: venv
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.8
  - nbconvert
  - pip:
    - git+https://github.com/xyz/abcgit
```

the containerization fails with

```
#12 23.07 Installing pip packages: git+https://github.com/xyz/abc.git
#12 23.72 Collecting git+https://github.com/xyz/abc.git (from -r /tmp/mambafLLMJROqlZM (line 1))
#12 23.72   Cloning https://github.com/xyz/abc.git to ./pip-req-build-0ajqy1b_
#12 23.72   ERROR: Error [Errno 2] No such file or directory: 'git' while executing command git version
#12 23.72 ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?
#12 23.87 critical libmamba pip failed to install packages
```

unless the base image contains `git`.

This is not the case anywhere except with the `laserfarm` flavor.

To support pip installs from git sources, we need to add `git` to the conda environments of all flavors.
